### ISSUE TITLE
Show error if something's wrong

### ISSUE THREAD

**Issue by Lex-2008** [Lex-2008/pkc#1]
If something's wrong, we just log error message to console without anything visible to user, like this: https://github.com/Lex-2008/pkc/blob/master/decrypt.html#L60

We should show a nice message to user, instead.

**Comment by rileythomp** [comment]
I think I can do this for you tonight.

**Comment by Lex-2008** [comment]
Thanks! Implementation is up to you - even replacing `console.log` with `alert` would be an improvement comparing to what we have now, but having some HTML dialog would be awesome!

**Comment by rileythomp** [comment]
Created PR #3 for this @Lex-2008

**Comment by Lex-2008** [comment]
Thanks! Sorry I missed github notifications for this repo. Change looks good!
